In [1]:
# https://machinelearningmastery.com/tutorial-first-neural-network-python-keras/
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
import numpy as np
# fix random seed for reproducibility
np.random.seed(0)
nb_classes = 12

Using TensorFlow backend.


In [2]:
# data_processed.csv
# load pima indians dataset
df = pd.read_csv('data_processed.csv')
# Get testSet
df_test = df.sample(frac=0.2, random_state=47)
df_test.to_csv('testSet.csv', index=False)
# Subtract to get trainingSet
df_train = df[~df.index.isin(df_test.index)]
df_train.to_csv('trainingSet.csv', index=False)

In [3]:
trainingSet = pd.read_csv('trainingSet.csv')
testSet = pd.read_csv('testSet.csv')

In [4]:
Y_train_raw = np.array(trainingSet['Value'])
trainSet_X = trainingSet.drop('Value', axis=1)
X_train = np.array(trainSet_X)
Y_train  = np.zeros((len(trainSet_X), nb_classes))
print Y_train_raw
for i in range(len(Y_train_raw)):
    Y_train[i][Y_train_raw[i] - 1] = 1.0
print X_train.shape

[2 2 3 ... 5 2 1]
(4850, 921)


In [5]:
Y_test = np.array(testSet['Value'])
testSet_X = testSet.drop('Value', axis=1)
X_test = np.array(testSet_X)
Y_test = Y_test - [1]

In [6]:
# create model
nb_classes = 12
model = Sequential()
model.add(Dense(1024, input_dim=921, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.05))
model.add(Dense(128, activation='relu'))
# model.add(Dropout(0.25))
model.add(Dense(64, activation='relu'))
# model.add(Dropout(0.25))
model.add(Dense(32, activation='relu'))
# model.add(Dropout(0.25))
model.add(Dense(nb_classes))
model.add(Activation('softmax'))

#model.add(Dense(2, activation='relu'))
#model.add(Dense(1, activation='sigmoid'))
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [7]:
# print X_train
# print Y_train
# Fit the model
model.fit(X_train, Y_train, epochs=10, batch_size=10, shuffle=True, class_weight='auto',)

Instructions for updating:
Use tf.cast instead.
Epoch 1/10
4850/4850 [==============================] - 7s 1ms/step - loss: 0.2212 - acc: 0.9160
Epoch 2/10
4850/4850 [==============================] - 4s 904us/step - loss: 0.1960 - acc: 0.9176
Epoch 3/10
4850/4850 [==============================] - 5s 930us/step - loss: 0.1875 - acc: 0.9196
Epoch 4/10
4850/4850 [==============================] - 4s 903us/step - loss: 0.1857 - acc: 0.9203
Epoch 5/10
4850/4850 [==============================] - 4s 865us/step - loss: 0.1801 - acc: 0.9216
Epoch 6/10
4850/4850 [==============================] - 4s 927us/step - loss: 0.1763 - acc: 0.9230
Epoch 7/10
4850/4850 [==============================] - 5s 955us/step - loss: 0.1760 - acc: 0.9239
Epoch 8/10
4850/4850 [==============================] - 5s 953us/step - loss: 0.1723 - acc: 0.9243
Epoch 9/10
4850/4850 [==============================] - 4s 927us/step - loss: 0.1726 - acc: 0.9248
Epoch 10/10
4850/4850 [==============================] - 4s 877

In [8]:
raw_predictions = model.predict(X_test, batch_size=10, verbose=0)
print raw_predictions
predicted = np.argmax(raw_predictions, axis=1)

[[4.07639854e-02 1.24706574e-01 3.01734537e-01 ... 6.86554858e-06
  4.86468309e-07 1.55040038e-06]
 [5.32559335e-01 4.36409026e-01 3.06994412e-02 ... 3.46217114e-13
  5.23755606e-14 8.66412383e-14]
 [5.09624660e-01 3.51843506e-01 1.14310868e-01 ... 4.94248252e-06
  2.67291171e-06 2.89314266e-06]
 ...
 [4.81708311e-02 1.35596961e-01 2.96843499e-01 ... 1.44529749e-05
  1.28101385e-06 3.70906378e-06]
 [5.35143912e-01 3.36417377e-01 1.06975250e-01 ... 4.12774307e-06
  2.32212142e-06 2.46509353e-06]
 [1.17443465e-02 3.24139781e-02 8.96830037e-02 ... 3.15717026e-03
  3.65061947e-04 5.27158147e-04]]


In [9]:
count = 0
print Y_test
for i in range(len(Y_test)):
    if predicted[i] == Y_test[i]:
        count += 1
print 1.0 * count/len(Y_test)

[3 0 0 ... 2 0 5]
0.463696369637


In [10]:
# print np.count_nonzero(Y_test)

#testSet['Value'].value_counts()
print testSet['Value'].value_counts()

1     387
2     309
3     150
4     107
6      96
5      75
7      35
8      28
9      12
11      6
10      6
12      1
Name: Value, dtype: int64


In [11]:
print Y_test

[3 0 0 ... 2 0 5]
